<?xml version="1.0" encoding="utf-8"?><Database Name="CybageConnectDB" Class="CybageConnectLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GVC1390\MSSQLSERVER2019;Initial Catalog=CybageConnectDB;User ID=sa;Encrypt=False" SettingsObjectName="CybageConnect.Properties.Settings" SettingsPropertyName="CybageConnectDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserRegistration" Member="UserRegistrations">
    <Type Name="UserRegistration">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="UserRegistration_ArticlesOfUser" Member="ArticlesOfUsers" ThisKey="UserId" OtherKey="UserId" Type="ArticlesOfUser" />
      <Association Name="UserRegistration_BlogsOfUser" Member="BlogsOfUsers" ThisKey="UserId" OtherKey="UserId" Type="BlogsOfUser" />
      <Association Name="UserRegistration_ProjectInsightsOfUser" Member="ProjectInsightsOfUsers" ThisKey="UserId" OtherKey="UserId" Type="ProjectInsightsOfUser" />
      <Association Name="UserRegistration_connection" Member="connections" ThisKey="UserId" OtherKey="UserId" Type="connection" />
      <Association Name="UserRegistration_FriendRequest" Member="FriendRequests" ThisKey="UserId" OtherKey="ReceiverId" Type="FriendRequest" />
      <Association Name="UserRegistration_FriendRequest1" Member="FriendRequests1" ThisKey="UserId" OtherKey="senderID" Type="FriendRequest" />
    </Type>
  </Table>
  <Table Name="dbo.ArticlesOfUsers" Member="ArticlesOfUsers">
    <Type Name="ArticlesOfUser">
      <Column Name="ArticleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Article" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PublishedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserRegistration_ArticlesOfUser" Member="UserRegistration" ThisKey="UserId" OtherKey="UserId" Type="UserRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogsOfUsers" Member="BlogsOfUsers">
    <Type Name="BlogsOfUser">
      <Column Name="BlogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Blog" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PublishedDateOfBLog" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserRegistration_BlogsOfUser" Member="UserRegistration" ThisKey="UserId" OtherKey="UserId" Type="UserRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectInsightsOfUsers" Member="ProjectInsightsOfUsers">
    <Type Name="ProjectInsightsOfUser">
      <Column Name="ProjectInsightId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectInsight" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PublishedDateOfProjectInsight" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserRegistration_ProjectInsightsOfUser" Member="UserRegistration" ThisKey="UserId" OtherKey="UserId" Type="UserRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.connections" Member="connections">
    <Type Name="connection">
      <Column Name="ConnectId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RqstCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserRegistration_connection" Member="UserRegistration" ThisKey="UserId" OtherKey="UserId" Type="UserRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FriendRequests" Member="FriendRequests">
    <Type Name="FriendRequest">
      <Column Name="ReqId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="senderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiverId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RqstMessage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="UserRegistration_FriendRequest" Member="UserRegistration" ThisKey="ReceiverId" OtherKey="UserId" Type="UserRegistration" IsForeignKey="true" />
      <Association Name="UserRegistration_FriendRequest1" Member="UserRegistration1" ThisKey="senderID" OtherKey="UserId" Type="UserRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.OnAccept" Method="OnAccept">
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Ondelete" Method="Ondelete">
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SendRequest" Method="SendRequest">
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>